import React, { useState } from "react";
import {Tabs, Tab, Pagination} from '@mui/material';
import UploadImageCard from "./subtools/UploadImageCard";
import { PUBLIC_URL } from "../../utils/Constant";

const itemsPerPage = 36;
const gallery = [
    {
        category: "Background",
        items: [
            "https://atomicecovers.s3.amazonaws.com/1705699931066chess.png",
            "https://atomicecovers.s3.amazonaws.com/1705693579229dog-made-by-artist.JPEG",
            `${PUBLIC_URL}/stockimage/Background/Background (1).png`,
            `${PUBLIC_URL}/stockimage/Background/Background (2).png`,
            `${PUBLIC_URL}/stockimage/Background/Background (3).png`,
            `${PUBLIC_URL}/stockimage/Background/Background (4).png`,
        ]
    },
    {
        category: "Animals & Wildlife",
        items: [
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (1).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (2).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (3).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (4).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (5).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (6).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (7).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (8).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (9).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (10).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (11).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (12).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (13).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (14).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (15).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (16).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (17).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (18).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (19).png`,
            `${PUBLIC_URL}/stockimage/Animals & Wildlife/Animals & Wildlife (20).png`,
        ]
    },
    {
        category: "Fantasy & Science Fiction",
        items: [
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (1).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (2).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (3).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (4).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (5).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (6).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (7).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (8).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (9).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (10).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (11).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (12).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (13).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (14).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (15).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (16).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (17).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (18).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (19).png`,
            `${PUBLIC_URL}/stockimage/Fantasy & Science Fiction/Fantasy & Science Fiction (20).png`,
        ]
    },
    {
        category: "Nature & Landscapes",
        items: [
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (1).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (2).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (3).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (4).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (5).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (6).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (7).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (8).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (9).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (10).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (11).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (12).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (13).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (14).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (15).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (16).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (17).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (18).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (19).png`,
            `${PUBLIC_URL}/stockimage/Nature & Landscapes/Nature & Landscapes (20).png`,
        ]
    },
    {
        category: "People",
        items: [
            `${PUBLIC_URL}/stockimage/People/People (1).png`,
            `${PUBLIC_URL}/stockimage/People/People (2).png`,
            `${PUBLIC_URL}/stockimage/People/People (3).png`,
            `${PUBLIC_URL}/stockimage/People/People (4).png`,
            `${PUBLIC_URL}/stockimage/People/People (5).png`,
            `${PUBLIC_URL}/stockimage/People/People (6).png`,
            `${PUBLIC_URL}/stockimage/People/People (7).png`,
            `${PUBLIC_URL}/stockimage/People/People (8).png`,
            `${PUBLIC_URL}/stockimage/People/People (9).png`,
            `${PUBLIC_URL}/stockimage/People/People (10).png`,
            `${PUBLIC_URL}/stockimage/People/People (11).png`,
            `${PUBLIC_URL}/stockimage/People/People (12).png`,
            `${PUBLIC_URL}/stockimage/People/People (13).png`,
            `${PUBLIC_URL}/stockimage/People/People (14).png`,
            `${PUBLIC_URL}/stockimage/People/People (15).png`,
            `${PUBLIC_URL}/stockimage/People/People (16).png`,
            `${PUBLIC_URL}/stockimage/People/People (17).png`,
            `${PUBLIC_URL}/stockimage/People/People (18).png`,
            `${PUBLIC_URL}/stockimage/People/People (19).png`,
            `${PUBLIC_URL}/stockimage/People/People (20).png`,
        ]
    },
    {
        category: "Wealth",
        items: [
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (1).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (2).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (3).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (4).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (5).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (6).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (7).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (8).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (9).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (10).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (11).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (12).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (13).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (14).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (15).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (16).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (17).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (18).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (19).png`,
            `${PUBLIC_URL}/stockimage/Wealth/Wealth (20).png`,
        ]
    },
    {
        category: "Wealth16-9",
        items: [
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth16-9/Wealth16-9 (48).jpg`
        ]
    },
    {
        category: "Wealth9-16",
        items: [
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (48).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (49).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (50).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (51).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (52).jpg`,
            `${PUBLIC_URL}/stockimage/Wealth9-16/Wealth9-16 (53).jpg`
        ]
    },
    {
        category: "Badge Style Images",
        items: [
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (1).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (2).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (3).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (4).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (5).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (6).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (7).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (8).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (9).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (10).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (11).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (12).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (13).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (14).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (15).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (16).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (17).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (18).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (19).png`,
            `${PUBLIC_URL}/stockimage/Badge Style Images/Badge Style Images (20).png`,
        ]
    },
    {
        category: "Dogs9-16",
        items: [
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (48).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (49).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (50).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (51).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (52).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (53).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (54).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (55).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (56).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (57).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (58).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs9-16/Dogs9-16 (59).jpg`
        ]
    },
    {
        category: "Dogs16-9",
        items: [
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (48).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (49).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (50).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (51).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (52).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (53).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (54).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (55).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (56).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (57).jpg`,
            `${PUBLIC_URL}/stockimage/Dogs16-9/Dogs16-9 (58).jpg`
        ]
    },
    {
        category: "Fruits9-16",
        items: [
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (48).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (49).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (50).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (51).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (52).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (53).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (54).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits9-16/Fruits9-16 (55).jpg`
        ]
    },
    {
        category: "Fruits16-9",
        items: [
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (48).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (49).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (50).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (51).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (52).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (53).jpg`,
            `${PUBLIC_URL}/stockimage/Fruits16-9/Fruits16-9 (54).jpg`
        ]
    },
    {
        category: "Midjourney",
        items: [
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (1).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (2).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (3).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (4).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (5).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (6).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (7).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (8).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (9).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (10).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (11).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (12).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (13).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (14).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (15).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (16).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (17).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (18).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (19).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (20).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (21).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (22).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (23).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (24).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (25).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (26).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (27).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (28).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (29).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (30).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (31).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (32).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (33).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (34).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (35).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (36).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (37).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (38).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (39).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (40).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (41).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (42).jpg`,
            `${PUBLIC_URL}/stockimage/Midjourney/Midjourney (43).jpg`
        ]
    },
    {
        category: "Miscellaneous",
        items: [
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (1).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (2).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (3).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (4).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (5).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (6).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (7).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (8).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (9).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (10).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (11).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (12).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (13).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (14).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (15).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (16).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (17).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (18).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (19).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (20).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (21).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (22).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (23).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (24).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (25).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (26).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (27).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (28).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (29).png`,
            `${PUBLIC_URL}/stockimage/Miscellaneous/Miscellaneous (30).png`
        ]
    },
    {
        category: "Random Objects and Food",
        items: [
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (1).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (2).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (3).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (4).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (5).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (6).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (7).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (8).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (9).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (10).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (11).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (12).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (13).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (14).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (15).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (16).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (17).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (18).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (19).png`,
            `${PUBLIC_URL}/stockimage/Random Objects and Food/Random Objects and Food (20).png`,
        ]
    },
    {
        category: "Research Lab",
        items: [
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (1).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (2).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (3).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (4).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (5).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (6).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (7).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (8).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (9).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (10).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (11).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (12).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (13).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (14).jpg`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (15).png`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (16).png`,
            `${PUBLIC_URL}/stockimage/Research Lab/Research Lab (17).png`
        ]
    },
    {
        category: "Scientist9-16",
        items: [
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist9-16/Scientist9-16 (41).jpg`
        ]
    },
    {
        category: "Scientist16-9",
        items: [
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (1).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (2).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (3).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (4).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (5).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (6).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (7).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (8).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (9).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (10).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (11).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (12).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (13).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (14).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (15).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (16).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (17).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (18).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (19).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (20).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (21).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (22).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (23).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (24).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (25).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (26).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (27).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (28).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (29).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (30).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (31).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (32).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (33).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (34).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (35).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (36).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (37).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (38).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (39).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (40).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (41).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (42).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (43).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (44).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (45).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (46).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (47).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (48).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (49).jpg`,
            `${PUBLIC_URL}/stockimage/Scientist16-9/Scientist16-9 (50).jpg`
        ]
    },
    {
        category: "Technology & Innovation",
        items: [
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (1).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (2).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (3).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (4).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (5).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (6).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (7).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (8).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (9).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (10).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (11).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (12).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (13).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (14).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (15).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (16).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (17).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (18).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (19).png`,
            `${PUBLIC_URL}/stockimage/Technology & Innovation/Technology & Innovation (20).png`,
        ]
    },
    {
        category: "Unica Tool",
        items: [
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (1).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (2).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (3).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (4).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (5).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (6).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (7).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (8).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (9).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (10).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (11).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (12).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (13).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (14).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (15).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (16).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (17).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (18).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (19).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (20).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (21).png`,
            `${PUBLIC_URL}/stockimage/Unica Tool/Unica Tool (22).png`,
        ]
    },
]

//// StockImagesPage component connected with StockImages tab on create cover page
const StockImagesPage = ({setBgImageSelected, setStockImagesSelected, setBackgroundSelected}) => {
    const [value, setValue] = useState(0);
    const [pageValue, setPageValue] = useState(1);
    const [indexGallery, setIndexGallery] = useState(0);
    const [count, setCount]= useState(Math.ceil(gallery[0].items.length/itemsPerPage));

    const handleChange = (event, newValue) =>{
        setValue(newValue);
        setIndexGallery(newValue);
        setPageValue(1);
        setCount(Math.ceil(gallery[newValue].items.length/itemsPerPage))
    }

    const handleChangePage = (event, newPage) => {
        setPageValue(newPage);
    }

    function a11yProps(index) {
        return {
          id: `vertical-tab-${index}`,
          'aria-controls': `vertical-tabpanel-${index}`,
        };
      }

    return (
        <div className="stock-gallery-container">
            <div className="stock-category">
                <Tabs
                    orientation="vertical"
                    variant="scrollable"
                    value={value}
                    onChange={handleChange}
                    aria-label="Vertical tabs example"
                    
                >
                    {
                        gallery.map((category, index)=>{
                            return <Tab 
                                        key={index}
                                        label={category.category} 
                                        style={{backgroundColor: '#2e7d32'}} 
                                        className="stock-category-item" 
                                        {...a11yProps(index)}
                                    />        
                        })
                    }
                </Tabs>
            </div>
            <div className="stock-images">
                <div className="stock-images-pagination-container">
                    <Pagination 
                        count={count} 
                        page={pageValue} 
                        variant="outlined" 
                        shape="rounded"
                        onChange={handleChangePage}
                        className='stock-images-pagination'/>
                </div>
                <div className="stock-images-content upload-page-body">
                    {
                        gallery[indexGallery]
                            .items
                            .slice(
                                itemsPerPage*(pageValue-1), 
                                itemsPerPage*(pageValue))
                            .map((image, index)=>{
                                return <UploadImageCard 
                                    url={image} 
                                    key={index} 
                                    setBackgroundSelected={setBackgroundSelected} 
                                    setBgImageSelected={setBgImageSelected} 
                                    setUploadImagesSelected={setStockImagesSelected} />
                        })
                    }
                </div>
            </div>
        </div>
    )
}

export default StockImagesPage;